### ISSUE TITLE
referenced *.js content not present in module

### ISSUE THREAD

**Issue by arlac77** [tgdwyer/WebCola#203]
Somehow the module content is only present as *.ts not *.js:
main -> WebCola/index.js  -> WebCola/src/adaptor.js  (<- missing)

**Comment by aspiers** [comment]
IIUC this is supposed to be addressed already by #199.  However this only works if the caller's `package.json` contains a reference to the github repo as (incorrectly) documented in `README.md`:

```json
"dependencies": {
  "webcola": "tgdwyer/WebCola#master"
}
```

(Note that it is `"webcola"` not `"cola"` as mentioned in the `README.md`.)

If I change it to

```json
"dependencies": {
  "webcola": "~3.3.0"
}
```

and re-run my `browserify` command then I get:

```
Error: Cannot find module './src/adaptor' from '/home/adam/.GIT/adamspiers.org/git-deps/html/node_modules/webcola/WebCola'
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:42:25
    at load (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:43)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:66:22
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:21:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Running a recursive diff between the resulting 3.3.0 and git `master` trees shows that 3.3.0 was actually published from 90bd3749afc4298eea2d295871b8422eaf5d3f3b, but this is actually older then 6703e492 which is pointed to by the `v3.3.0` tag, and the former crucially misses the merge of #199.  

So @tgdwyer can I suggest that you bump the version to 3.3.1, tag it as `v3.3.1`, and then `npm publish`?  Otherwise anyone installing by version number will get this breakage.  Thanks!
